openapi: "3.0.0"
info:
  title: "This is a sample api"
  version: null
  description: null
servers:
- "https://api.example.com/v1"
- "https://api.example.com/v1"
paths: null
components:
  schemas: null
  securitySchemes: null
security: null
