openapi: "3.0.0"
info:
  title: "This is a sample api"
  version: "1.0"
  description: "top level description for api"
servers:
- "https://api.example.com/v1"
paths: null
components:
  schemas: null
  securitySchemes: null
security: null
